import { WorkflowNode } from '@/store/workflowStore'
import { Edge } from '@xyflow/react'

export interface WorkflowTemplate {
  id: string
  name: string
  description: string
  category: string
  tags?: string[]
  difficulty?: 'beginner' | 'intermediate' | 'advanced' | 'expert'
  estimatedTime?: string
  useCases?: string[]
  nodes: WorkflowNode[]
  edges: Edge[]
}

export const templateCategories = {
  starter: {
    name: 'Starter Templates',
    description: 'Simple workflows to get you started',
    icon: '🚀',
  },
  data: {
    name: 'Data Processing',
    description: 'ETL, transformation, and data pipeline workflows',
    icon: '📊',
  },
  advanced: {
    name: 'Advanced AI',
    description: 'Complex AI workflows with multiple models',
    icon: '🧠',
  },
  automation: {
    name: 'Automation',
    description: 'Automated workflows for various tasks',
    icon: '⚙️',
  },
  media: {
    name: 'Media Processing',
    description: 'Image, video, and audio processing workflows',
    icon: '🎨',
  },
  rag: {
    name: 'RAG Systems',
    description: 'Retrieval-Augmented Generation workflows',
    icon: '📚',
  },
  integration: {
    name: 'Integrations',
    description: 'Connect to external services and APIs',
    icon: '🔌',
  },
} as const

export const workflowTemplates: WorkflowTemplate[] = [
  {
    id: 'simple-ai-pipeline',
    name: 'Simple AI Pipeline',
    description: 'Basic workflow with trigger, AI processing, and output',
    category: 'starter',
    nodes: [
      {
        id: 'trigger-1',
        type: 'custom',
        position: { x: 50, y: 100 },
        data: {
          label: 'Text Input',
          type: 'textInput',
          status: 'idle',
          config: {},
        },
      },
      {
        id: 'ai-1',
        type: 'custom',
        position: { x: 300, y: 100 },
        data: {
          label: 'OpenAI GPT-4',
          type: 'openai',
          status: 'idle',
          config: {
            model: 'gpt-4o-mini',
            prompt: 'Process the input data',
          },
        },
      },
      {
        id: 'output-1',
        type: 'custom',
        position: { x: 550, y: 100 },
        data: {
          label: 'Console Output',
          type: 'console',
          status: 'idle',
          config: {},
        },
      },
    ],
    edges: [
      {
        id: 'e1-2',
        source: 'trigger-1',
        target: 'ai-1',
        type: 'default',
      },
      {
        id: 'e2-3',
        source: 'ai-1',
        target: 'output-1',
        type: 'default',
      },
    ],
  },
  {
    id: 'rag-pipeline',
    name: 'RAG Pipeline',
    description: 'Complete retrieval-augmented generation workflow with embeddings and vector search',
    category: 'advanced',
    nodes: [
      {
        id: 'doc-input',
        type: 'custom',
        position: { x: 50, y: 100 },
        data: {
          label: 'PDF Extract',
          type: 'pdfExtract',
          status: 'idle',
          config: {},
        },
      },
      {
        id: 'chunk-1',
        type: 'custom',
        position: { x: 250, y: 100 },
        data: {
          label: 'Text Chunker',
          type: 'textChunker',
          status: 'idle',
          config: { chunkSize: 500, overlap: 50 },
        },
      },
      {
        id: 'embed-1',
        type: 'custom',
        position: { x: 450, y: 100 },
        data: {
          label: 'Embeddings',
          type: 'embeddings',
          status: 'idle',
          config: { model: 'text-embedding-ada-002' },
        },
      },
      {
        id: 'vector-1',
        type: 'custom',
        position: { x: 650, y: 100 },
        data: {
          label: 'ChromaDB Store',
          type: 'chromadb',
          status: 'idle',
          config: {},
        },
      },
      {
        id: 'query-input',
        type: 'custom',
        position: { x: 50, y: 250 },
        data: {
          label: 'User Query',
          type: 'textInput',
          status: 'idle',
          config: {},
        },
      },
      {
        id: 'embed-2',
        type: 'custom',
        position: { x: 250, y: 250 },
        data: {
          label: 'Query Embedding',
          type: 'embeddings',
          status: 'idle',
          config: { model: 'text-embedding-ada-002' },
        },
      },
      {
        id: 'vector-search',
        type: 'custom',
        position: { x: 450, y: 250 },
        data: {
          label: 'Vector Search',
          type: 'chromadb',
          status: 'idle',
          config: { operation: 'search', k: 5 },
        },
      },
      {
        id: 'rag-ai',
        type: 'custom',
        position: { x: 650, y: 250 },
        data: {
          label: 'GPT-4 RAG',
          type: 'openai',
          status: 'idle',
          config: {
            model: 'gpt-4o',
            prompt: 'Answer based on context',
          },
        },
      },
      {
        id: 'output-1',
        type: 'custom',
        position: { x: 850, y: 250 },
        data: {
          label: 'Response',
          type: 'console',
          status: 'idle',
          config: {},
        },
      },
    ],
    edges: [
      { id: 'e1-2', source: 'doc-input', target: 'chunk-1', type: 'default' },
      { id: 'e2-3', source: 'chunk-1', target: 'embed-1', type: 'default' },
      { id: 'e3-4', source: 'embed-1', target: 'vector-1', type: 'default' },
      { id: 'e5-6', source: 'query-input', target: 'embed-2', type: 'default' },
      { id: 'e6-7', source: 'embed-2', target: 'vector-search', type: 'default' },
      { id: 'e7-8', source: 'vector-search', target: 'rag-ai', type: 'default' },
      { id: 'e8-9', source: 'rag-ai', target: 'output-1', type: 'default' },
    ],
  },
  {
    id: 'document-processing',
    name: '📄 Document Processing',
    description: 'PDF → Text → Summary → Translate → Output',
    category: 'data',
    nodes: [
      {
        id: 'file-1',
        type: 'custom',
        position: { x: 50, y: 150 },
        data: {
          label: 'File Upload',
          type: 'fileUpload',
          status: 'idle',
          config: {},
        },
      },
      {
        id: 'pdf-1',
        type: 'custom',
        position: { x: 250, y: 150 },
        data: {
          label: 'PDF Extract',
          type: 'pdfExtract',
          status: 'idle',
          config: {},
        },
      },
      {
        id: 'chunk-1',
        type: 'custom',
        position: { x: 450, y: 150 },
        data: {
          label: 'Text Chunker',
          type: 'textChunker',
          status: 'idle',
          config: { chunkSize: 1000 },
        },
      },
      {
        id: 'summary-1',
        type: 'custom',
        position: { x: 650, y: 150 },
        data: {
          label: 'Summarize',
          type: 'summarize',
          status: 'idle',
          config: {},
        },
      },
      {
        id: 'translate-1',
        type: 'custom',
        position: { x: 850, y: 150 },
        data: {
          label: 'Translate',
          type: 'translate',
          status: 'idle',
          config: { target: 'en' },
        },
      },
      {
        id: 'write-1',
        type: 'custom',
        position: { x: 1050, y: 150 },
        data: {
          label: 'File Write',
          type: 'fileWrite',
          status: 'idle',
          config: {},
        },
      },
    ],
    edges: [
      { id: 'e1-2', source: 'file-1', target: 'pdf-1', type: 'default' },
      { id: 'e2-3', source: 'pdf-1', target: 'chunk-1', type: 'default' },
      { id: 'e3-4', source: 'chunk-1', target: 'summary-1', type: 'default' },
      { id: 'e4-5', source: 'summary-1', target: 'translate-1', type: 'default' },
      { id: 'e5-6', source: 'translate-1', target: 'write-1', type: 'default' },
    ],
  },
  {
    id: 'multi-agent-system',
    name: '👥 Multi-Agent System',
    description: 'Input → [OpenAI + Claude + Gemini] → Merge → Synthesizer → Output',
    category: 'advanced',
    nodes: [
      {
        id: 'task-input',
        type: 'custom',
        position: { x: 50, y: 200 },
        data: {
          label: 'Task Input',
          type: 'textInput',
          status: 'idle',
          config: {},
        },
      },
      {
        id: 'openai-1',
        type: 'custom',
        position: { x: 300, y: 100 },
        data: {
          label: 'OpenAI GPT-4',
          type: 'openai',
          status: 'idle',
          config: { model: 'gpt-4o' },
        },
      },
      {
        id: 'claude-1',
        type: 'custom',
        position: { x: 300, y: 200 },
        data: {
          label: 'Claude 3.5',
          type: 'anthropicClaude',
          status: 'idle',
          config: {},
        },
      },
      {
        id: 'gemini-1',
        type: 'custom',
        position: { x: 300, y: 300 },
        data: {
          label: 'Google Gemini',
          type: 'googleGemini',
          status: 'idle',
          config: {},
        },
      },
      {
        id: 'merge-1',
        type: 'custom',
        position: { x: 550, y: 200 },
        data: {
          label: 'Merge Results',
          type: 'merge',
          status: 'idle',
          config: {},
        },
      },
      {
        id: 'synthesizer',
        type: 'custom',
        position: { x: 750, y: 200 },
        data: {
          label: 'Synthesizer',
          type: 'openai',
          status: 'idle',
          config: { model: 'gpt-4o', task: 'synthesize' },
        },
      },
      {
        id: 'output',
        type: 'custom',
        position: { x: 950, y: 200 },
        data: {
          label: 'Final Output',
          type: 'console',
          status: 'idle',
          config: {},
        },
      },
    ],
    edges: [
      { id: 'e1-2', source: 'task-input', target: 'openai-1', type: 'default' },
      { id: 'e1-3', source: 'task-input', target: 'claude-1', type: 'default' },
      { id: 'e1-4', source: 'task-input', target: 'gemini-1', type: 'default' },
      { id: 'e2-5', source: 'openai-1', target: 'merge-1', type: 'default' },
      { id: 'e3-5', source: 'claude-1', target: 'merge-1', type: 'default' },
      { id: 'e4-5', source: 'gemini-1', target: 'merge-1', type: 'default' },
      { id: 'e5-6', source: 'merge-1', target: 'synthesizer', type: 'default' },
      { id: 'e6-7', source: 'synthesizer', target: 'output', type: 'default' },
    ],
  },
  {
    id: 'web-scraping-pipeline',
    name: 'Web Scraping Pipeline',
    description: 'Scrape websites, extract data, and store results',
    category: 'data',
    nodes: [
      {
        id: 'scraper-1',
        type: 'custom',
        position: { x: 50, y: 150 },
        data: {
          label: 'Web Scraper',
          type: 'webScraper',
          status: 'idle',
          config: { url: 'https://example.com' },
        },
      },
      {
        id: 'regex-1',
        type: 'custom',
        position: { x: 250, y: 150 },
        data: {
          label: 'Regex Extract',
          type: 'regexExtract',
          status: 'idle',
          config: { pattern: '.*' },
        },
      },
      {
        id: 'json-1',
        type: 'custom',
        position: { x: 450, y: 100 },
        data: {
          label: 'JSON Transform',
          type: 'jsonTransform',
          status: 'idle',
          config: {},
        },
      },
      {
        id: 'validate-1',
        type: 'custom',
        position: { x: 450, y: 200 },
        data: {
          label: 'Validator',
          type: 'validator',
          status: 'idle',
          config: {},
        },
      },
      {
        id: 'db-1',
        type: 'custom',
        position: { x: 650, y: 150 },
        data: {
          label: 'PostgreSQL',
          type: 'postgresql',
          status: 'idle',
          config: {},
        },
      },
      {
        id: 'webhook-1',
        type: 'custom',
        position: { x: 850, y: 150 },
        data: {
          label: 'Webhook',
          type: 'webhook',
          status: 'idle',
          config: {},
        },
      },
    ],
    edges: [
      { id: 'e1-2', source: 'scraper-1', target: 'regex-1', type: 'default' },
      { id: 'e2-3', source: 'regex-1', target: 'json-1', type: 'default' },
      { id: 'e2-4', source: 'regex-1', target: 'validate-1', type: 'default' },
      { id: 'e3-5', source: 'json-1', target: 'db-1', type: 'default' },
      { id: 'e4-5', source: 'validate-1', target: 'db-1', type: 'default' },
      { id: 'e5-6', source: 'db-1', target: 'webhook-1', type: 'default' },
    ],
  },
  {
    id: 'image-generation-workflow',
    name: '🎨 Image Generation',
    description: 'Text Prompt → Enhance → Image Gen → S3 Upload → Notification',
    category: 'media',
    nodes: [
      {
        id: 'prompt-1',
        type: 'custom',
        position: { x: 50, y: 150 },
        data: {
          label: 'Prompt Input',
          type: 'textInput',
          status: 'idle',
          config: {},
        },
      },
      {
        id: 'enhance-1',
        type: 'custom',
        position: { x: 250, y: 150 },
        data: {
          label: 'Enhance Prompt',
          type: 'openai',
          status: 'idle',
          config: { model: 'gpt-4o-mini', task: 'enhance_prompt' },
        },
      },
      {
        id: 'dalle-1',
        type: 'custom',
        position: { x: 450, y: 150 },
        data: {
          label: 'DALL-E 3',
          type: 'dalle',
          status: 'idle',
          config: {},
        },
      },
      {
        id: 's3-1',
        type: 'custom',
        position: { x: 650, y: 150 },
        data: {
          label: 'S3 Upload',
          type: 's3Upload',
          status: 'idle',
          config: {},
        },
      },
      {
        id: 'notify-1',
        type: 'custom',
        position: { x: 850, y: 150 },
        data: {
          label: 'Desktop Notification',
          type: 'desktopNotification',
          status: 'idle',
          config: {},
        },
      },
    ],
    edges: [
      { id: 'e1-2', source: 'prompt-1', target: 'enhance-1', type: 'default' },
      { id: 'e2-3', source: 'enhance-1', target: 'dalle-1', type: 'default' },
      { id: 'e3-4', source: 'dalle-1', target: 's3-1', type: 'default' },
      { id: 'e4-5', source: 's3-1', target: 'notify-1', type: 'default' },
    ],
  },
  {
    id: 'social-media-automation',
    name: '🤳 Social Media Bot',
    description: 'RSS → Summarize → AI Enhancement → Twitter Post',
    category: 'automation',
    nodes: [
      {
        id: 'rss-1',
        type: 'custom',
        position: { x: 50, y: 150 },
        data: {
          label: 'RSS Reader',
          type: 'rssReader',
          status: 'idle',
          config: {},
        },
      },
      {
        id: 'summarize-1',
        type: 'custom',
        position: { x: 250, y: 150 },
        data: {
          label: 'Summarize',
          type: 'summarize',
          status: 'idle',
          config: {},
        },
      },
      {
        id: 'ai-enhance-1',
        type: 'custom',
        position: { x: 450, y: 150 },
        data: {
          label: 'AI Enhancement',
          type: 'openai',
          status: 'idle',
          config: { model: 'gpt-4o-mini', task: 'enhance_post' },
        },
      },
      {
        id: 'twitter-1',
        type: 'custom',
        position: { x: 650, y: 150 },
        data: {
          label: 'Twitter Post',
          type: 'twitter',
          status: 'idle',
          config: {},
        },
      },
    ],
    edges: [
      { id: 'e1-2', source: 'rss-1', target: 'summarize-1', type: 'default' },
      { id: 'e2-3', source: 'summarize-1', target: 'ai-enhance-1', type: 'default' },
      { id: 'e3-4', source: 'ai-enhance-1', target: 'twitter-1', type: 'default' },
    ],
  },
  {
    id: 'voice-transcription-pipeline',
    name: 'Voice Transcription Pipeline',
    description: 'Transcribe audio, analyze, and distribute results',
    category: 'media',
    nodes: [
      {
        id: 'audio-1',
        type: 'custom',
        position: { x: 50, y: 150 },
        data: {
          label: 'Voice Input',
          type: 'voiceInput',
          status: 'idle',
          config: {},
        },
      },
      {
        id: 'whisper-1',
        type: 'custom',
        position: { x: 250, y: 150 },
        data: {
          label: 'Whisper AI',
          type: 'whisper',
          status: 'idle',
          config: {},
        },
      },
      {
        id: 'sentiment-1',
        type: 'custom',
        position: { x: 450, y: 100 },
        data: {
          label: 'Sentiment',
          type: 'sentimentAnalysis',
          status: 'idle',
          config: {},
        },
      },
      {
        id: 'translate-1',
        type: 'custom',
        position: { x: 450, y: 200 },
        data: {
          label: 'Translate',
          type: 'translate',
          status: 'idle',
          config: { target: 'es' },
        },
      },
      {
        id: 'sheets-1',
        type: 'custom',
        position: { x: 650, y: 150 },
        data: {
          label: 'Google Sheets',
          type: 'googleSheets',
          status: 'idle',
          config: {},
        },
      },
    ],
    edges: [
      { id: 'e1-2', source: 'audio-1', target: 'whisper-1', type: 'default' },
      { id: 'e2-3', source: 'whisper-1', target: 'sentiment-1', type: 'default' },
      { id: 'e2-4', source: 'whisper-1', target: 'translate-1', type: 'default' },
      { id: 'e3-5', source: 'sentiment-1', target: 'sheets-1', type: 'default' },
      { id: 'e4-5', source: 'translate-1', target: 'sheets-1', type: 'default' },
    ],
  },
  {
    id: 'data-enrichment',
    name: 'Data Enrichment Pipeline',
    description: 'Load, transform, enrich, and store data across multiple databases',
    category: 'data',
    nodes: [
      {
        id: 'csv-1',
        type: 'custom',
        position: { x: 50, y: 200 },
        data: {
          label: 'CSV Reader',
          type: 'csvReader',
          status: 'idle',
          config: {},
        },
      },
      {
        id: 'clean-1',
        type: 'custom',
        position: { x: 250, y: 200 },
        data: {
          label: 'Clean Data',
          type: 'textTransform',
          status: 'idle',
          config: {},
        },
      },
      {
        id: 'api-1',
        type: 'custom',
        position: { x: 450, y: 150 },
        data: {
          label: 'API Request',
          type: 'apiRequest',
          status: 'idle',
          config: {},
        },
      },
      {
        id: 'merge-1',
        type: 'custom',
        position: { x: 450, y: 250 },
        data: {
          label: 'Merge Data',
          type: 'merge',
          status: 'idle',
          config: {},
        },
      },
      {
        id: 'mongo-1',
        type: 'custom',
        position: { x: 650, y: 150 },
        data: {
          label: 'MongoDB',
          type: 'mongodb',
          status: 'idle',
          config: {},
        },
      },
      {
        id: 'redis-1',
        type: 'custom',
        position: { x: 650, y: 250 },
        data: {
          label: 'Redis Cache',
          type: 'redis',
          status: 'idle',
          config: {},
        },
      },
      {
        id: 'airtable-1',
        type: 'custom',
        position: { x: 850, y: 200 },
        data: {
          label: 'Airtable',
          type: 'airtable',
          status: 'idle',
          config: {},
        },
      },
    ],
    edges: [
      { id: 'e1-2', source: 'csv-1', target: 'clean-1', type: 'default' },
      { id: 'e2-3', source: 'clean-1', target: 'api-1', type: 'default' },
      { id: 'e2-4', source: 'clean-1', target: 'merge-1', type: 'default' },
      { id: 'e3-4', source: 'api-1', target: 'merge-1', type: 'default' },
      { id: 'e4-5', source: 'merge-1', target: 'mongo-1', type: 'default' },
      { id: 'e4-6', source: 'merge-1', target: 'redis-1', type: 'default' },
      { id: 'e5-7', source: 'mongo-1', target: 'airtable-1', type: 'default' },
      { id: 'e6-7', source: 'redis-1', target: 'airtable-1', type: 'default' },
    ],
  },
  {
    id: 'ai-model-comparison',
    name: 'AI Model Comparison',
    description: 'Compare responses from multiple AI providers',
    category: 'advanced',
    nodes: [
      {
        id: 'input-1',
        type: 'custom',
        position: { x: 50, y: 250 },
        data: {
          label: 'Prompt Input',
          type: 'textInput',
          status: 'idle',
          config: {},
        },
      },
      {
        id: 'openai-1',
        type: 'custom',
        position: { x: 300, y: 100 },
        data: {
          label: 'OpenAI GPT-4',
          type: 'openai',
          status: 'idle',
          config: { model: 'gpt-4o' },
        },
      },
      {
        id: 'claude-1',
        type: 'custom',
        position: { x: 300, y: 175 },
        data: {
          label: 'Claude 3.5',
          type: 'anthropicClaude',
          status: 'idle',
          config: {},
        },
      },
      {
        id: 'gemini-1',
        type: 'custom',
        position: { x: 300, y: 250 },
        data: {
          label: 'Google Gemini',
          type: 'googleGemini',
          status: 'idle',
          config: {},
        },
      },
      {
        id: 'mistral-1',
        type: 'custom',
        position: { x: 300, y: 325 },
        data: {
          label: 'Mistral',
          type: 'mistral',
          status: 'idle',
          config: {},
        },
      },
      {
        id: 'groq-1',
        type: 'custom',
        position: { x: 300, y: 400 },
        data: {
          label: 'Groq',
          type: 'groq',
          status: 'idle',
          config: {},
        },
      },
      {
        id: 'judge-1',
        type: 'custom',
        position: { x: 550, y: 250 },
        data: {
          label: 'AI Judge',
          type: 'openai',
          status: 'idle',
          config: { model: 'gpt-4o', task: 'compare' },
        },
      },
      {
        id: 'output-1',
        type: 'custom',
        position: { x: 750, y: 250 },
        data: {
          label: 'Results',
          type: 'console',
          status: 'idle',
          config: {},
        },
      },
    ],
    edges: [
      { id: 'e1-2', source: 'input-1', target: 'openai-1', type: 'default' },
      { id: 'e1-3', source: 'input-1', target: 'claude-1', type: 'default' },
      { id: 'e1-4', source: 'input-1', target: 'gemini-1', type: 'default' },
      { id: 'e1-5', source: 'input-1', target: 'mistral-1', type: 'default' },
      { id: 'e1-6', source: 'input-1', target: 'groq-1', type: 'default' },
      { id: 'e2-7', source: 'openai-1', target: 'judge-1', type: 'default' },
      { id: 'e3-7', source: 'claude-1', target: 'judge-1', type: 'default' },
      { id: 'e4-7', source: 'gemini-1', target: 'judge-1', type: 'default' },
      { id: 'e5-7', source: 'mistral-1', target: 'judge-1', type: 'default' },
      { id: 'e6-7', source: 'groq-1', target: 'judge-1', type: 'default' },
      { id: 'e7-8', source: 'judge-1', target: 'output-1', type: 'default' },
    ],
  },
  {
    id: 'error-handling-retry',
    name: 'Error Handling & Retry',
    description: 'Robust workflow with error handling, retry logic, and fallbacks',
    category: 'advanced',
    nodes: [
      {
        id: 'api-1',
        type: 'custom',
        position: { x: 50, y: 150 },
        data: {
          label: 'API Request',
          type: 'apiRequest',
          status: 'idle',
          config: {},
        },
      },
      {
        id: 'retry-1',
        type: 'custom',
        position: { x: 250, y: 150 },
        data: {
          label: 'Retry Logic',
          type: 'retry',
          status: 'idle',
          config: { maxRetries: 3 },
        },
      },
      {
        id: 'cache-1',
        type: 'custom',
        position: { x: 450, y: 100 },
        data: {
          label: 'Cache',
          type: 'cache',
          status: 'idle',
          config: {},
        },
      },
      {
        id: 'error-1',
        type: 'custom',
        position: { x: 450, y: 200 },
        data: {
          label: 'Error Handler',
          type: 'errorHandler',
          status: 'idle',
          config: {},
        },
      },
      {
        id: 'logger-1',
        type: 'custom',
        position: { x: 650, y: 200 },
        data: {
          label: 'Logger',
          type: 'logger',
          status: 'idle',
          config: {},
        },
      },
      {
        id: 'email-1',
        type: 'custom',
        position: { x: 850, y: 200 },
        data: {
          label: 'Email Alert',
          type: 'email',
          status: 'idle',
          config: {},
        },
      },
    ],
    edges: [
      { id: 'e1-2', source: 'api-1', target: 'retry-1', type: 'default' },
      { id: 'e2-3', source: 'retry-1', target: 'cache-1', type: 'default' },
      { id: 'e2-4', source: 'retry-1', target: 'error-1', type: 'default', label: 'on error' },
      { id: 'e4-5', source: 'error-1', target: 'logger-1', type: 'default' },
      { id: 'e5-6', source: 'logger-1', target: 'email-1', type: 'default' },
    ],
  },
  {
    id: 'github-automation',
    name: 'GitHub Automation',
    description: 'Monitor GitHub repos, analyze code, and create automated reports',
    category: 'automation',
    nodes: [
      {
        id: 'github-1',
        type: 'custom',
        position: { x: 50, y: 150 },
        data: {
          label: 'GitHub Repo',
          type: 'githubRepo',
          status: 'idle',
          config: {},
        },
      },
      {
        id: 'filter-1',
        type: 'custom',
        position: { x: 250, y: 150 },
        data: {
          label: 'Filter',
          type: 'filter',
          status: 'idle',
          config: { criteria: 'new_commits' },
        },
      },
      {
        id: 'ai-1',
        type: 'custom',
        position: { x: 450, y: 150 },
        data: {
          label: 'Code Review AI',
          type: 'openai',
          status: 'idle',
          config: { model: 'gpt-4o' },
        },
      },
      {
        id: 'template-1',
        type: 'custom',
        position: { x: 650, y: 100 },
        data: {
          label: 'Report Template',
          type: 'template',
          status: 'idle',
          config: {},
        },
      },
      {
        id: 'slack-1',
        type: 'custom',
        position: { x: 650, y: 200 },
        data: {
          label: 'Slack Notify',
          type: 'slack',
          status: 'idle',
          config: {},
        },
      },
    ],
    edges: [
      { id: 'e1-2', source: 'github-1', target: 'filter-1', type: 'default' },
      { id: 'e2-3', source: 'filter-1', target: 'ai-1', type: 'default' },
      { id: 'e3-4', source: 'ai-1', target: 'template-1', type: 'default' },
      { id: 'e3-5', source: 'ai-1', target: 'slack-1', type: 'default' },
    ],
  },
  {
    id: 'sentiment-analysis',
    name: '📊 Sentiment Analysis',
    description: 'Analyze sentiment from social media and generate reports',
    category: 'data',
    nodes: [
      {
        id: 'twitter-1',
        type: 'custom',
        position: { x: 50, y: 150 },
        data: {
          label: 'Twitter API',
          type: 'twitter',
          status: 'idle',
          config: {},
        },
      },
      {
        id: 'sentiment-1',
        type: 'custom',
        position: { x: 250, y: 150 },
        data: {
          label: 'Sentiment Analysis',
          type: 'sentimentAnalysis',
          status: 'idle',
          config: {},
        },
      },
      {
        id: 'filter-1',
        type: 'custom',
        position: { x: 450, y: 150 },
        data: {
          label: 'Filter Positive',
          type: 'filter',
          status: 'idle',
          config: { criteria: 'positive' },
        },
      },
      {
        id: 'db-1',
        type: 'custom',
        position: { x: 650, y: 150 },
        data: {
          label: 'PostgreSQL',
          type: 'postgresql',
          status: 'idle',
          config: {},
        },
      },
      {
        id: 'sheets-1',
        type: 'custom',
        position: { x: 850, y: 150 },
        data: {
          label: 'Google Sheets',
          type: 'googleSheets',
          status: 'idle',
          config: {},
        },
      },
    ],
    edges: [
      { id: 'e1-2', source: 'twitter-1', target: 'sentiment-1', type: 'default' },
      { id: 'e2-3', source: 'sentiment-1', target: 'filter-1', type: 'default' },
      { id: 'e3-4', source: 'filter-1', target: 'db-1', type: 'default' },
      { id: 'e4-5', source: 'db-1', target: 'sheets-1', type: 'default' },
    ],
  },
  {
    id: 'voice-assistant',
    name: '🎤 Voice Assistant',
    description: 'Complete voice assistant with speech-to-text and text-to-speech',
    category: 'media',
    nodes: [
      {
        id: 'voice-1',
        type: 'custom',
        position: { x: 50, y: 150 },
        data: {
          label: 'Voice Input',
          type: 'voiceInput',
          status: 'idle',
          config: {},
        },
      },
      {
        id: 'whisper-1',
        type: 'custom',
        position: { x: 250, y: 150 },
        data: {
          label: 'Whisper STT',
          type: 'whisper',
          status: 'idle',
          config: {},
        },
      },
      {
        id: 'ai-1',
        type: 'custom',
        position: { x: 450, y: 150 },
        data: {
          label: 'OpenAI GPT-4',
          type: 'openai',
          status: 'idle',
          config: { model: 'gpt-4o' },
        },
      },
      {
        id: 'eleven-1',
        type: 'custom',
        position: { x: 650, y: 150 },
        data: {
          label: 'ElevenLabs TTS',
          type: 'elevenlabs',
          status: 'idle',
          config: {},
        },
      },
      {
        id: 'output-1',
        type: 'custom',
        position: { x: 850, y: 150 },
        data: {
          label: 'Audio Output',
          type: 'console',
          status: 'idle',
          config: {},
        },
      },
    ],
    edges: [
      { id: 'e1-2', source: 'voice-1', target: 'whisper-1', type: 'default' },
      { id: 'e2-3', source: 'whisper-1', target: 'ai-1', type: 'default' },
      { id: 'e3-4', source: 'ai-1', target: 'eleven-1', type: 'default' },
      { id: 'e4-5', source: 'eleven-1', target: 'output-1', type: 'default' },
    ],
  },
  {
    id: 'code-review-assistant',
    name: '💻 Code Review Assistant',
    description: 'Automated code review with AI analysis and notifications',
    category: 'automation',
    nodes: [
      {
        id: 'github-1',
        type: 'custom',
        position: { x: 50, y: 150 },
        data: {
          label: 'GitHub Repo',
          type: 'githubRepo',
          status: 'idle',
          config: {},
        },
      },
      {
        id: 'chunk-1',
        type: 'custom',
        position: { x: 250, y: 150 },
        data: {
          label: 'Code Chunker',
          type: 'textChunker',
          status: 'idle',
          config: { chunkSize: 1000 },
        },
      },
      {
        id: 'claude-1',
        type: 'custom',
        position: { x: 450, y: 150 },
        data: {
          label: 'Claude Review',
          type: 'anthropicClaude',
          status: 'idle',
          config: { task: 'code_review' },
        },
      },
      {
        id: 'template-1',
        type: 'custom',
        position: { x: 650, y: 150 },
        data: {
          label: 'Format Report',
          type: 'template',
          status: 'idle',
          config: {},
        },
      },
      {
        id: 'slack-1',
        type: 'custom',
        position: { x: 850, y: 150 },
        data: {
          label: 'Slack Notify',
          type: 'slack',
          status: 'idle',
          config: {},
        },
      },
    ],
    edges: [
      { id: 'e1-2', source: 'github-1', target: 'chunk-1', type: 'default' },
      { id: 'e2-3', source: 'chunk-1', target: 'claude-1', type: 'default' },
      { id: 'e3-4', source: 'claude-1', target: 'template-1', type: 'default' },
      { id: 'e4-5', source: 'template-1', target: 'slack-1', type: 'default' },
    ],
  },
  {
    id: 'etl-pipeline',
    name: '🔄 ETL Pipeline',
    description: 'Extract, Transform, Load data across multiple systems',
    category: 'data',
    nodes: [
      {
        id: 'api-1',
        type: 'custom',
        position: { x: 50, y: 150 },
        data: {
          label: 'API Request',
          type: 'apiRequest',
          status: 'idle',
          config: {},
        },
      },
      {
        id: 'json-1',
        type: 'custom',
        position: { x: 250, y: 150 },
        data: {
          label: 'JSON Parse',
          type: 'jsonParser',
          status: 'idle',
          config: {},
        },
      },
      {
        id: 'transform-1',
        type: 'custom',
        position: { x: 450, y: 150 },
        data: {
          label: 'Transform Data',
          type: 'jsonTransform',
          status: 'idle',
          config: {},
        },
      },
      {
        id: 'db-1',
        type: 'custom',
        position: { x: 650, y: 100 },
        data: {
          label: 'PostgreSQL',
          type: 'postgresql',
          status: 'idle',
          config: {},
        },
      },
      {
        id: 'sheets-1',
        type: 'custom',
        position: { x: 650, y: 200 },
        data: {
          label: 'Google Sheets',
          type: 'googleSheets',
          status: 'idle',
          config: {},
        },
      },
    ],
    edges: [
      { id: 'e1-2', source: 'api-1', target: 'json-1', type: 'default' },
      { id: 'e2-3', source: 'json-1', target: 'transform-1', type: 'default' },
      { id: 'e3-4', source: 'transform-1', target: 'db-1', type: 'default' },
      { id: 'e3-5', source: 'transform-1', target: 'sheets-1', type: 'default' },
    ],
  },
  {
    id: 'email-automation',
    name: '📧 Email Automation',
    description: 'Automated email processing and response generation',
    category: 'automation',
    nodes: [
      {
        id: 'email-1',
        type: 'custom',
        position: { x: 50, y: 150 },
        data: {
          label: 'Email Input',
          type: 'email',
          status: 'idle',
          config: {},
        },
      },
      {
        id: 'ai-1',
        type: 'custom',
        position: { x: 250, y: 150 },
        data: {
          label: 'Process Email',
          type: 'openai',
          status: 'idle',
          config: { model: 'gpt-4o-mini' },
        },
      },
      {
        id: 'template-1',
        type: 'custom',
        position: { x: 450, y: 150 },
        data: {
          label: 'Email Template',
          type: 'template',
          status: 'idle',
          config: {},
        },
      },
      {
        id: 'send-1',
        type: 'custom',
        position: { x: 650, y: 150 },
        data: {
          label: 'Send Email',
          type: 'email',
          status: 'idle',
          config: {},
        },
      },
    ],
    edges: [
      { id: 'e1-2', source: 'email-1', target: 'ai-1', type: 'default' },
      { id: 'e2-3', source: 'ai-1', target: 'template-1', type: 'default' },
      { id: 'e3-4', source: 'template-1', target: 'send-1', type: 'default' },
    ],
  },
  {
    id: 'research-assistant',
    name: '🔬 Research Assistant',
    description: 'Automated research with web search and report generation',
    category: 'advanced',
    nodes: [
      {
        id: 'query-1',
        type: 'custom',
        position: { x: 50, y: 150 },
        data: {
          label: 'Research Query',
          type: 'textInput',
          status: 'idle',
          config: {},
        },
      },
      {
        id: 'search-1',
        type: 'custom',
        position: { x: 250, y: 150 },
        data: {
          label: 'Web Search',
          type: 'webScraper',
          status: 'idle',
          config: {},
        },
      },
      {
        id: 'extract-1',
        type: 'custom',
        position: { x: 450, y: 150 },
        data: {
          label: 'Extract Data',
          type: 'regexExtract',
          status: 'idle',
          config: {},
        },
      },
      {
        id: 'summarize-1',
        type: 'custom',
        position: { x: 650, y: 150 },
        data: {
          label: 'Summarize',
          type: 'summarize',
          status: 'idle',
          config: {},
        },
      },
      {
        id: 'report-1',
        type: 'custom',
        position: { x: 850, y: 150 },
        data: {
          label: 'Generate Report',
          type: 'fileWrite',
          status: 'idle',
          config: {},
        },
      },
    ],
    edges: [
      { id: 'e1-2', source: 'query-1', target: 'search-1', type: 'default' },
      { id: 'e2-3', source: 'search-1', target: 'extract-1', type: 'default' },
      { id: 'e3-4', source: 'extract-1', target: 'summarize-1', type: 'default' },
      { id: 'e4-5', source: 'summarize-1', target: 'report-1', type: 'default' },
    ],
  },
  {
    id: 'web-scraping-ai',
    name: '🌐 Web Scraping + AI',
    description: 'Scrape websites, analyze with AI, and send reports',
    category: 'data',
    nodes: [
      {
        id: 'url-1',
        type: 'custom',
        position: { x: 50, y: 150 },
        data: {
          label: 'URL Input',
          type: 'textInput',
          status: 'idle',
          config: {},
        },
      },
      {
        id: 'scraper-1',
        type: 'custom',
        position: { x: 250, y: 150 },
        data: {
          label: 'Web Scraper',
          type: 'webScraper',
          status: 'idle',
          config: {},
        },
      },
      {
        id: 'chunk-1',
        type: 'custom',
        position: { x: 450, y: 150 },
        data: {
          label: 'Text Chunker',
          type: 'textChunker',
          status: 'idle',
          config: {},
        },
      },
      {
        id: 'ai-1',
        type: 'custom',
        position: { x: 650, y: 150 },
        data: {
          label: 'AI Analysis',
          type: 'openai',
          status: 'idle',
          config: { model: 'gpt-4o' },
        },
      },
      {
        id: 'report-1',
        type: 'custom',
        position: { x: 850, y: 100 },
        data: {
          label: 'Generate Report',
          type: 'template',
          status: 'idle',
          config: {},
        },
      },
      {
        id: 'email-1',
        type: 'custom',
        position: { x: 850, y: 200 },
        data: {
          label: 'Send Email',
          type: 'email',
          status: 'idle',
          config: {},
        },
      },
    ],
    edges: [
      { id: 'e1-2', source: 'url-1', target: 'scraper-1', type: 'default' },
      { id: 'e2-3', source: 'scraper-1', target: 'chunk-1', type: 'default' },
      { id: 'e3-4', source: 'chunk-1', target: 'ai-1', type: 'default' },
      { id: 'e4-5', source: 'ai-1', target: 'report-1', type: 'default' },
      { id: 'e4-6', source: 'ai-1', target: 'email-1', type: 'default' },
    ],
  },
  {
    id: 'cohere-embeddings-search',
    name: '🔍 Cohere Semantic Search',
    description: 'Build semantic search with Cohere embeddings and reranking',
    category: 'advanced',
    nodes: [
      {
        id: 'docs-1',
        type: 'custom',
        position: { x: 50, y: 100 },
        data: {
          label: 'Document Upload',
          type: 'fileUpload',
          status: 'idle',
          config: {},
        },
      },
      {
        id: 'chunk-1',
        type: 'custom',
        position: { x: 250, y: 100 },
        data: {
          label: 'Text Chunker',
          type: 'textChunker',
          status: 'idle',
          config: { chunkSize: 512 },
        },
      },
      {
        id: 'cohere-embed-1',
        type: 'custom',
        position: { x: 450, y: 100 },
        data: {
          label: 'Cohere Embeddings',
          type: 'cohere',
          status: 'idle',
          config: { task: 'embed' },
        },
      },
      {
        id: 'weaviate-1',
        type: 'custom',
        position: { x: 650, y: 100 },
        data: {
          label: 'Weaviate Store',
          type: 'weaviate',
          status: 'idle',
          config: {},
        },
      },
      {
        id: 'query-1',
        type: 'custom',
        position: { x: 50, y: 250 },
        data: {
          label: 'Search Query',
          type: 'textInput',
          status: 'idle',
          config: {},
        },
      },
      {
        id: 'cohere-embed-2',
        type: 'custom',
        position: { x: 250, y: 250 },
        data: {
          label: 'Query Embedding',
          type: 'cohere',
          status: 'idle',
          config: { task: 'embed' },
        },
      },
      {
        id: 'search-1',
        type: 'custom',
        position: { x: 450, y: 250 },
        data: {
          label: 'Vector Search',
          type: 'weaviate',
          status: 'idle',
          config: { operation: 'search' },
        },
      },
      {
        id: 'cohere-rerank',
        type: 'custom',
        position: { x: 650, y: 250 },
        data: {
          label: 'Cohere Rerank',
          type: 'cohere',
          status: 'idle',
          config: { task: 'rerank' },
        },
      },
      {
        id: 'output-1',
        type: 'custom',
        position: { x: 850, y: 250 },
        data: {
          label: 'Results',
          type: 'console',
          status: 'idle',
          config: {},
        },
      },
    ],
    edges: [
      { id: 'e1-2', source: 'docs-1', target: 'chunk-1', type: 'default' },
      { id: 'e2-3', source: 'chunk-1', target: 'cohere-embed-1', type: 'default' },
      { id: 'e3-4', source: 'cohere-embed-1', target: 'weaviate-1', type: 'default' },
      { id: 'e5-6', source: 'query-1', target: 'cohere-embed-2', type: 'default' },
      { id: 'e6-7', source: 'cohere-embed-2', target: 'search-1', type: 'default' },
      { id: 'e7-8', source: 'search-1', target: 'cohere-rerank', type: 'default' },
      { id: 'e8-9', source: 'cohere-rerank', target: 'output-1', type: 'default' },
    ],
  },
  {
    id: 'ollama-local-ai',
    name: '🏠 Local AI with Ollama',
    description: 'Run AI models locally with Ollama for privacy and cost savings',
    category: 'advanced',
    nodes: [
      {
        id: 'input-1',
        type: 'custom',
        position: { x: 50, y: 150 },
        data: {
          label: 'User Input',
          type: 'textInput',
          status: 'idle',
          config: {},
        },
      },
      {
        id: 'ollama-1',
        type: 'custom',
        position: { x: 250, y: 150 },
        data: {
          label: 'Ollama Llama3',
          type: 'ollama',
          status: 'idle',
          config: { model: 'llama3' },
        },
      },
      {
        id: 'cache-1',
        type: 'custom',
        position: { x: 450, y: 150 },
        data: {
          label: 'Cache Response',
          type: 'cache',
          status: 'idle',
          config: {},
        },
      },
      {
        id: 'db-1',
        type: 'custom',
        position: { x: 650, y: 100 },
        data: {
          label: 'SQLite Store',
          type: 'sqlite',
          status: 'idle',
          config: {},
        },
      },
      {
        id: 'output-1',
        type: 'custom',
        position: { x: 650, y: 200 },
        data: {
          label: 'Display Result',
          type: 'console',
          status: 'idle',
          config: {},
        },
      },
    ],
    edges: [
      { id: 'e1-2', source: 'input-1', target: 'ollama-1', type: 'default' },
      { id: 'e2-3', source: 'ollama-1', target: 'cache-1', type: 'default' },
      { id: 'e3-4', source: 'cache-1', target: 'db-1', type: 'default' },
      { id: 'e3-5', source: 'cache-1', target: 'output-1', type: 'default' },
    ],
  },
  {
    id: 'perplexity-research',
    name: '🔬 Perplexity Research Engine',
    description: 'Use Perplexity AI for real-time web research and fact-checking',
    category: 'advanced',
    nodes: [
      {
        id: 'topic-1',
        type: 'custom',
        position: { x: 50, y: 150 },
        data: {
          label: 'Research Topic',
          type: 'textInput',
          status: 'idle',
          config: {},
        },
      },
      {
        id: 'perplexity-1',
        type: 'custom',
        position: { x: 250, y: 150 },
        data: {
          label: 'Perplexity Search',
          type: 'perplexity',
          status: 'idle',
          config: { model: 'sonar-pro' },
        },
      },
      {
        id: 'entity-1',
        type: 'custom',
        position: { x: 450, y: 100 },
        data: {
          label: 'Extract Entities',
          type: 'entityExtraction',
          status: 'idle',
          config: {},
        },
      },
      {
        id: 'summarize-1',
        type: 'custom',
        position: { x: 450, y: 200 },
        data: {
          label: 'Summarize',
          type: 'summarize',
          status: 'idle',
          config: {},
        },
      },
      {
        id: 'template-1',
        type: 'custom',
        position: { x: 650, y: 150 },
        data: {
          label: 'Format Report',
          type: 'template',
          status: 'idle',
          config: {},
        },
      },
      {
        id: 'notion-1',
        type: 'custom',
        position: { x: 850, y: 100 },
        data: {
          label: 'Save to Notion',
          type: 'notion',
          status: 'idle',
          config: {},
        },
      },
      {
        id: 'email-1',
        type: 'custom',
        position: { x: 850, y: 200 },
        data: {
          label: 'Email Report',
          type: 'email',
          status: 'idle',
          config: {},
        },
      },
    ],
    edges: [
      { id: 'e1-2', source: 'topic-1', target: 'perplexity-1', type: 'default' },
      { id: 'e2-3', source: 'perplexity-1', target: 'entity-1', type: 'default' },
      { id: 'e2-4', source: 'perplexity-1', target: 'summarize-1', type: 'default' },
      { id: 'e3-5', source: 'entity-1', target: 'template-1', type: 'default' },
      { id: 'e4-5', source: 'summarize-1', target: 'template-1', type: 'default' },
      { id: 'e5-6', source: 'template-1', target: 'notion-1', type: 'default' },
      { id: 'e5-7', source: 'template-1', target: 'email-1', type: 'default' },
    ],
  },
  {
    id: 'replicate-image-pipeline',
    name: '🎨 Replicate Multi-Model Pipeline',
    description: 'Generate, enhance, and upscale images using Replicate models',
    category: 'media',
    nodes: [
      {
        id: 'prompt-1',
        type: 'custom',
        position: { x: 50, y: 150 },
        data: {
          label: 'Image Prompt',
          type: 'textInput',
          status: 'idle',
          config: {},
        },
      },
      {
        id: 'replicate-1',
        type: 'custom',
        position: { x: 250, y: 150 },
        data: {
          label: 'SD XL Generate',
          type: 'replicate',
          status: 'idle',
          config: { model: 'sdxl' },
        },
      },
      {
        id: 'replicate-2',
        type: 'custom',
        position: { x: 450, y: 150 },
        data: {
          label: 'Real-ESRGAN Upscale',
          type: 'replicate',
          status: 'idle',
          config: { model: 'real-esrgan' },
        },
      },
      {
        id: 'vision-1',
        type: 'custom',
        position: { x: 650, y: 150 },
        data: {
          label: 'GPT-4 Vision QA',
          type: 'gpt4Vision',
          status: 'idle',
          config: { task: 'describe' },
        },
      },
      {
        id: 's3-1',
        type: 'custom',
        position: { x: 850, y: 100 },
        data: {
          label: 'S3 Upload',
          type: 's3Upload',
          status: 'idle',
          config: {},
        },
      },
      {
        id: 'discord-1',
        type: 'custom',
        position: { x: 850, y: 200 },
        data: {
          label: 'Discord Share',
          type: 'discord',
          status: 'idle',
          config: {},
        },
      },
    ],
    edges: [
      { id: 'e1-2', source: 'prompt-1', target: 'replicate-1', type: 'default' },
      { id: 'e2-3', source: 'replicate-1', target: 'replicate-2', type: 'default' },
      { id: 'e3-4', source: 'replicate-2', target: 'vision-1', type: 'default' },
      { id: 'e4-5', source: 'vision-1', target: 's3-1', type: 'default' },
      { id: 'e4-6', source: 'vision-1', target: 'discord-1', type: 'default' },
    ],
  },
  {
    id: 'together-ai-ensemble',
    name: '🤝 Together AI Ensemble',
    description: 'Parallel processing with multiple models via Together AI',
    category: 'advanced',
    nodes: [
      {
        id: 'input-1',
        type: 'custom',
        position: { x: 50, y: 250 },
        data: {
          label: 'Prompt Input',
          type: 'textInput',
          status: 'idle',
          config: {},
        },
      },
      {
        id: 'together-1',
        type: 'custom',
        position: { x: 300, y: 100 },
        data: {
          label: 'Llama-3.1 70B',
          type: 'togetherAI',
          status: 'idle',
          config: { model: 'llama-3.1-70b' },
        },
      },
      {
        id: 'together-2',
        type: 'custom',
        position: { x: 300, y: 200 },
        data: {
          label: 'Mixtral 8x7B',
          type: 'togetherAI',
          status: 'idle',
          config: { model: 'mixtral-8x7b' },
        },
      },
      {
        id: 'together-3',
        type: 'custom',
        position: { x: 300, y: 300 },
        data: {
          label: 'Qwen 2 72B',
          type: 'togetherAI',
          status: 'idle',
          config: { model: 'qwen-2-72b' },
        },
      },
      {
        id: 'together-4',
        type: 'custom',
        position: { x: 300, y: 400 },
        data: {
          label: 'DeepSeek Coder',
          type: 'togetherAI',
          status: 'idle',
          config: { model: 'deepseek-coder' },
        },
      },
      {
        id: 'merge-1',
        type: 'custom',
        position: { x: 550, y: 250 },
        data: {
          label: 'Merge Responses',
          type: 'merge',
          status: 'idle',
          config: {},
        },
      },
      {
        id: 'claude-1',
        type: 'custom',
        position: { x: 750, y: 250 },
        data: {
          label: 'Claude Final Review',
          type: 'anthropicClaude',
          status: 'idle',
          config: { task: 'synthesize' },
        },
      },
      {
        id: 'output-1',
        type: 'custom',
        position: { x: 950, y: 250 },
        data: {
          label: 'Final Output',
          type: 'console',
          status: 'idle',
          config: {},
        },
      },
    ],
    edges: [
      { id: 'e1-2', source: 'input-1', target: 'together-1', type: 'default' },
      { id: 'e1-3', source: 'input-1', target: 'together-2', type: 'default' },
      { id: 'e1-4', source: 'input-1', target: 'together-3', type: 'default' },
      { id: 'e1-5', source: 'input-1', target: 'together-4', type: 'default' },
      { id: 'e2-6', source: 'together-1', target: 'merge-1', type: 'default' },
      { id: 'e3-6', source: 'together-2', target: 'merge-1', type: 'default' },
      { id: 'e4-6', source: 'together-3', target: 'merge-1', type: 'default' },
      { id: 'e5-6', source: 'together-4', target: 'merge-1', type: 'default' },
      { id: 'e6-7', source: 'merge-1', target: 'claude-1', type: 'default' },
      { id: 'e7-8', source: 'claude-1', target: 'output-1', type: 'default' },
    ],
  },
  {
    id: 'groq-speed-pipeline',
    name: '⚡ Groq Ultra-Fast Pipeline',
    description: 'Lightning-fast inference with Groq for real-time applications',
    category: 'advanced',
    nodes: [
      {
        id: 'stream-1',
        type: 'custom',
        position: { x: 50, y: 150 },
        data: {
          label: 'Stream Input',
          type: 'textInput',
          status: 'idle',
          config: {},
        },
      },
      {
        id: 'groq-1',
        type: 'custom',
        position: { x: 250, y: 150 },
        data: {
          label: 'Groq Llama3 70B',
          type: 'groq',
          status: 'idle',
          config: { model: 'llama3-70b', streaming: true },
        },
      },
      {
        id: 'sentiment-1',
        type: 'custom',
        position: { x: 450, y: 100 },
        data: {
          label: 'Sentiment',
          type: 'sentimentAnalysis',
          status: 'idle',
          config: {},
        },
      },
      {
        id: 'conditional-1',
        type: 'custom',
        position: { x: 450, y: 200 },
        data: {
          label: 'Route by Sentiment',
          type: 'conditional',
          status: 'idle',
          config: {},
        },
      },
      {
        id: 'slack-1',
        type: 'custom',
        position: { x: 650, y: 100 },
        data: {
          label: 'Alert Slack',
          type: 'slack',
          status: 'idle',
          config: {},
        },
      },
      {
        id: 'logger-1',
        type: 'custom',
        position: { x: 650, y: 200 },
        data: {
          label: 'Log Result',
          type: 'logger',
          status: 'idle',
          config: {},
        },
      },
    ],
    edges: [
      { id: 'e1-2', source: 'stream-1', target: 'groq-1', type: 'default' },
      { id: 'e2-3', source: 'groq-1', target: 'sentiment-1', type: 'default' },
      { id: 'e2-4', source: 'groq-1', target: 'conditional-1', type: 'default' },
      { id: 'e3-5', source: 'sentiment-1', target: 'slack-1', type: 'default' },
      { id: 'e4-6', source: 'conditional-1', target: 'logger-1', type: 'default' },
    ],
  },
  {
    id: 'huggingface-nlp',
    name: '🤗 HuggingFace NLP Pipeline',
    description: 'Advanced NLP with HuggingFace transformers and custom models',
    category: 'advanced',
    nodes: [
      {
        id: 'text-1',
        type: 'custom',
        position: { x: 50, y: 200 },
        data: {
          label: 'Text Input',
          type: 'textInput',
          status: 'idle',
          config: {},
        },
      },
      {
        id: 'hf-1',
        type: 'custom',
        position: { x: 250, y: 100 },
        data: {
          label: 'HF Sentiment',
          type: 'huggingface',
          status: 'idle',
          config: { task: 'sentiment-analysis' },
        },
      },
      {
        id: 'hf-2',
        type: 'custom',
        position: { x: 250, y: 200 },
        data: {
          label: 'HF NER',
          type: 'huggingface',
          status: 'idle',
          config: { task: 'ner' },
        },
      },
      {
        id: 'hf-3',
        type: 'custom',
        position: { x: 250, y: 300 },
        data: {
          label: 'HF Summarization',
          type: 'huggingface',
          status: 'idle',
          config: { task: 'summarization' },
        },
      },
      {
        id: 'merge-1',
        type: 'custom',
        position: { x: 450, y: 200 },
        data: {
          label: 'Merge Analysis',
          type: 'merge',
          status: 'idle',
          config: {},
        },
      },
      {
        id: 'json-1',
        type: 'custom',
        position: { x: 650, y: 200 },
        data: {
          label: 'JSON Transform',
          type: 'jsonTransform',
          status: 'idle',
          config: {},
        },
      },
      {
        id: 'mongodb-1',
        type: 'custom',
        position: { x: 850, y: 200 },
        data: {
          label: 'MongoDB Store',
          type: 'mongodb',
          status: 'idle',
          config: {},
        },
      },
    ],
    edges: [
      { id: 'e1-2', source: 'text-1', target: 'hf-1', type: 'default' },
      { id: 'e1-3', source: 'text-1', target: 'hf-2', type: 'default' },
      { id: 'e1-4', source: 'text-1', target: 'hf-3', type: 'default' },
      { id: 'e2-5', source: 'hf-1', target: 'merge-1', type: 'default' },
      { id: 'e3-5', source: 'hf-2', target: 'merge-1', type: 'default' },
      { id: 'e4-5', source: 'hf-3', target: 'merge-1', type: 'default' },
      { id: 'e5-6', source: 'merge-1', target: 'json-1', type: 'default' },
      { id: 'e6-7', source: 'json-1', target: 'mongodb-1', type: 'default' },
    ],
  },
  {
    id: 'mistral-multilingual',
    name: '🌍 Mistral Multilingual Assistant',
    description: 'Multilingual content processing with Mistral AI',
    category: 'advanced',
    nodes: [
      {
        id: 'input-1',
        type: 'custom',
        position: { x: 50, y: 150 },
        data: {
          label: 'Multilingual Input',
          type: 'textInput',
          status: 'idle',
          config: {},
        },
      },
      {
        id: 'mistral-1',
        type: 'custom',
        position: { x: 250, y: 150 },
        data: {
          label: 'Mistral Large',
          type: 'mistral',
          status: 'idle',
          config: { model: 'mistral-large' },
        },
      },
      {
        id: 'translate-1',
        type: 'custom',
        position: { x: 450, y: 100 },
        data: {
          label: 'Translate to EN',
          type: 'translate',
          status: 'idle',
          config: { target: 'en' },
        },
      },
      {
        id: 'translate-2',
        type: 'custom',
        position: { x: 450, y: 150 },
        data: {
          label: 'Translate to ES',
          type: 'translate',
          status: 'idle',
          config: { target: 'es' },
        },
      },
      {
        id: 'translate-3',
        type: 'custom',
        position: { x: 450, y: 200 },
        data: {
          label: 'Translate to FR',
          type: 'translate',
          status: 'idle',
          config: { target: 'fr' },
        },
      },
      {
        id: 'sheets-1',
        type: 'custom',
        position: { x: 650, y: 150 },
        data: {
          label: 'Google Sheets',
          type: 'googleSheets',
          status: 'idle',
          config: {},
        },
      },
    ],
    edges: [
      { id: 'e1-2', source: 'input-1', target: 'mistral-1', type: 'default' },
      { id: 'e2-3', source: 'mistral-1', target: 'translate-1', type: 'default' },
      { id: 'e2-4', source: 'mistral-1', target: 'translate-2', type: 'default' },
      { id: 'e2-5', source: 'mistral-1', target: 'translate-3', type: 'default' },
      { id: 'e3-6', source: 'translate-1', target: 'sheets-1', type: 'default' },
      { id: 'e4-6', source: 'translate-2', target: 'sheets-1', type: 'default' },
      { id: 'e5-6', source: 'translate-3', target: 'sheets-1', type: 'default' },
    ],
  },
  {
    id: 'claude-vision-analyzer',
    name: '👁️ Claude Vision Analysis',
    description: 'Analyze images with Claude Vision and generate detailed reports',
    category: 'media',
    nodes: [
      {
        id: 'image-1',
        type: 'custom',
        position: { x: 50, y: 150 },
        data: {
          label: 'Image Upload',
          type: 'imageInput',
          status: 'idle',
          config: {},
        },
      },
      {
        id: 'claude-vision-1',
        type: 'custom',
        position: { x: 250, y: 150 },
        data: {
          label: 'Claude Vision',
          type: 'claudeVision',
          status: 'idle',
          config: { task: 'analyze' },
        },
      },
      {
        id: 'entity-1',
        type: 'custom',
        position: { x: 450, y: 100 },
        data: {
          label: 'Extract Entities',
          type: 'entityExtraction',
          status: 'idle',
          config: {},
        },
      },
      {
        id: 'summarize-1',
        type: 'custom',
        position: { x: 450, y: 200 },
        data: {
          label: 'Generate Summary',
          type: 'summarize',
          status: 'idle',
          config: {},
        },
      },
      {
        id: 'template-1',
        type: 'custom',
        position: { x: 650, y: 150 },
        data: {
          label: 'Report Template',
          type: 'template',
          status: 'idle',
          config: {},
        },
      },
      {
        id: 'pdf-1',
        type: 'custom',
        position: { x: 850, y: 150 },
        data: {
          label: 'Save as PDF',
          type: 'fileWrite',
          status: 'idle',
          config: { format: 'pdf' },
        },
      },
    ],
    edges: [
      { id: 'e1-2', source: 'image-1', target: 'claude-vision-1', type: 'default' },
      { id: 'e2-3', source: 'claude-vision-1', target: 'entity-1', type: 'default' },
      { id: 'e2-4', source: 'claude-vision-1', target: 'summarize-1', type: 'default' },
      { id: 'e3-5', source: 'entity-1', target: 'template-1', type: 'default' },
      { id: 'e4-5', source: 'summarize-1', target: 'template-1', type: 'default' },
      { id: 'e5-6', source: 'template-1', target: 'pdf-1', type: 'default' },
    ],
  },
  {
    id: 'gemini-multimodal',
    name: '🎭 Gemini Multimodal Studio',
    description: 'Process text, images, and video with Google Gemini',
    category: 'media',
    nodes: [
      {
        id: 'text-1',
        type: 'custom',
        position: { x: 50, y: 100 },
        data: {
          label: 'Text Input',
          type: 'textInput',
          status: 'idle',
          config: {},
        },
      },
      {
        id: 'image-1',
        type: 'custom',
        position: { x: 50, y: 175 },
        data: {
          label: 'Image Input',
          type: 'imageInput',
          status: 'idle',
          config: {},
        },
      },
      {
        id: 'video-1',
        type: 'custom',
        position: { x: 50, y: 250 },
        data: {
          label: 'Video Input',
          type: 'videoInput',
          status: 'idle',
          config: {},
        },
      },
      {
        id: 'gemini-1',
        type: 'custom',
        position: { x: 300, y: 175 },
        data: {
          label: 'Gemini Pro',
          type: 'googleGemini',
          status: 'idle',
          config: { model: 'gemini-1.5-pro', multimodal: true },
        },
      },
      {
        id: 'conditional-1',
        type: 'custom',
        position: { x: 500, y: 175 },
        data: {
          label: 'Content Filter',
          type: 'conditional',
          status: 'idle',
          config: {},
        },
      },
      {
        id: 'airtable-1',
        type: 'custom',
        position: { x: 700, y: 100 },
        data: {
          label: 'Airtable Store',
          type: 'airtable',
          status: 'idle',
          config: {},
        },
      },
      {
        id: 'telegram-1',
        type: 'custom',
        position: { x: 700, y: 250 },
        data: {
          label: 'Telegram Notify',
          type: 'telegram',
          status: 'idle',
          config: {},
        },
      },
    ],
    edges: [
      { id: 'e1-4', source: 'text-1', target: 'gemini-1', type: 'default' },
      { id: 'e2-4', source: 'image-1', target: 'gemini-1', type: 'default' },
      { id: 'e3-4', source: 'video-1', target: 'gemini-1', type: 'default' },
      { id: 'e4-5', source: 'gemini-1', target: 'conditional-1', type: 'default' },
      { id: 'e5-6', source: 'conditional-1', target: 'airtable-1', type: 'default' },
      { id: 'e5-7', source: 'conditional-1', target: 'telegram-1', type: 'default' },
    ],
  },
  {
    id: 'stable-diffusion-workflow',
    name: '🖼️ Stable Diffusion Art Studio',
    description: 'Create and refine AI art with Stable Diffusion and post-processing',
    category: 'media',
    nodes: [
      {
        id: 'prompt-1',
        type: 'custom',
        position: { x: 50, y: 150 },
        data: {
          label: 'Art Prompt',
          type: 'textInput',
          status: 'idle',
          config: {},
        },
      },
      {
        id: 'gemini-1',
        type: 'custom',
        position: { x: 250, y: 150 },
        data: {
          label: 'Enhance Prompt',
          type: 'googleGemini',
          status: 'idle',
          config: { task: 'enhance_art_prompt' },
        },
      },
      {
        id: 'sd-1',
        type: 'custom',
        position: { x: 450, y: 150 },
        data: {
          label: 'Stable Diffusion',
          type: 'stableDiffusion',
          status: 'idle',
          config: { model: 'sdxl-turbo' },
        },
      },
      {
        id: 'resize-1',
        type: 'custom',
        position: { x: 650, y: 100 },
        data: {
          label: 'Resize for Web',
          type: 'imageResize',
          status: 'idle',
          config: { width: 1920 },
        },
      },
      {
        id: 'resize-2',
        type: 'custom',
        position: { x: 650, y: 200 },
        data: {
          label: 'Thumbnail',
          type: 'imageResize',
          status: 'idle',
          config: { width: 400 },
        },
      },
      {
        id: 's3-1',
        type: 'custom',
        position: { x: 850, y: 100 },
        data: {
          label: 'S3 Upload',
          type: 's3Upload',
          status: 'idle',
          config: {},
        },
      },
      {
        id: 'whatsapp-1',
        type: 'custom',
        position: { x: 850, y: 200 },
        data: {
          label: 'WhatsApp Share',
          type: 'whatsapp',
          status: 'idle',
          config: {},
        },
      },
    ],
    edges: [
      { id: 'e1-2', source: 'prompt-1', target: 'gemini-1', type: 'default' },
      { id: 'e2-3', source: 'gemini-1', target: 'sd-1', type: 'default' },
      { id: 'e3-4', source: 'sd-1', target: 'resize-1', type: 'default' },
      { id: 'e3-5', source: 'sd-1', target: 'resize-2', type: 'default' },
      { id: 'e4-6', source: 'resize-1', target: 's3-1', type: 'default' },
      { id: 'e5-7', source: 'resize-2', target: 'whatsapp-1', type: 'default' },
    ],
  },
  {
    id: 'ai-powered-content-moderation',
    name: '🛡️ AI Content Moderation',
    description: 'Multi-provider content moderation with escalation workflow',
    category: 'automation',
    nodes: [
      {
        id: 'input-1',
        type: 'custom',
        position: { x: 50, y: 200 },
        data: {
          label: 'Content Input',
          type: 'textInput',
          status: 'idle',
          config: {},
        },
      },
      {
        id: 'gemini-1',
        type: 'custom',
        position: { x: 250, y: 150 },
        data: {
          label: 'Gemini Check',
          type: 'googleGemini',
          status: 'idle',
          config: { task: 'content_moderation' },
        },
      },
      {
        id: 'openai-1',
        type: 'custom',
        position: { x: 250, y: 250 },
        data: {
          label: 'OpenAI Check',
          type: 'openai',
          status: 'idle',
          config: { task: 'content_moderation' },
        },
      },
      {
        id: 'merge-1',
        type: 'custom',
        position: { x: 450, y: 200 },
        data: {
          label: 'Consensus',
          type: 'merge',
          status: 'idle',
          config: {},
        },
      },
      {
        id: 'conditional-1',
        type: 'custom',
        position: { x: 650, y: 200 },
        data: {
          label: 'Route Decision',
          type: 'conditional',
          status: 'idle',
          config: {},
        },
      },
      {
        id: 'postgresql-1',
        type: 'custom',
        position: { x: 850, y: 150 },
        data: {
          label: 'Approved DB',
          type: 'postgresql',
          status: 'idle',
          config: {},
        },
      },
      {
        id: 'email-1',
        type: 'custom',
        position: { x: 850, y: 250 },
        data: {
          label: 'Alert Moderator',
          type: 'email',
          status: 'idle',
          config: {},
        },
      },
    ],
    edges: [
      { id: 'e1-2', source: 'input-1', target: 'gemini-1', type: 'default' },
      { id: 'e1-3', source: 'input-1', target: 'openai-1', type: 'default' },
      { id: 'e2-4', source: 'gemini-1', target: 'merge-1', type: 'default' },
      { id: 'e3-4', source: 'openai-1', target: 'merge-1', type: 'default' },
      { id: 'e4-5', source: 'merge-1', target: 'conditional-1', type: 'default' },
      { id: 'e5-6', source: 'conditional-1', target: 'postgresql-1', type: 'default', label: 'approved' },
      { id: 'e5-7', source: 'conditional-1', target: 'email-1', type: 'default', label: 'flagged' },
    ],
  },
  {
    id: 'moa-system',
    name: '🧠 MOA (Mixture of Agents)',
    description: 'Advanced multi-model orchestration system for complex task processing with 2-3 AI models working in parallel',
    category: 'advanced',
    nodes: [
      {
        id: 'task-input',
        type: 'custom',
        position: { x: 50, y: 250 },
        data: {
          label: 'Complex Task Input',
          type: 'textInput',
          status: 'idle',
          config: {
            placeholder: 'Enter your complex task or query...',
          },
        },
      },
      {
        id: 'moa-coordinator',
        type: 'custom',
        position: { x: 250, y: 250 },
        data: {
          label: 'MOA Coordinator',
          type: 'moa',
          status: 'idle',
          config: {
            agents: [
              {
                id: 'agent-1',
                model: 'gpt-4o',
                provider: 'openai',
                prompt: 'Analyze the task from a technical perspective. Focus on implementation details, code quality, and best practices.',
                role: 'Technical Analyst',
              },
              {
                id: 'agent-2',
                model: 'claude-3-5-sonnet',
                provider: 'anthropicClaude',
                prompt: 'Analyze the task from a strategic perspective. Consider architecture, scalability, and long-term implications.',
                role: 'Strategic Advisor',
              },
              {
                id: 'agent-3',
                model: 'gemini-1.5-pro',
                provider: 'googleGemini',
                prompt: 'Analyze the task from a creative perspective. Suggest innovative approaches and alternative solutions.',
                role: 'Creative Consultant',
              },
            ],
            aggregationStrategy: 'weighted_consensus',
            includeAllResponses: true,
          },
        },
      },
      {
        id: 'agent-1-openai',
        type: 'custom',
        position: { x: 500, y: 100 },
        data: {
          label: 'OpenAI GPT-4o',
          type: 'openai',
          status: 'idle',
          config: {
            model: 'gpt-4o',
            prompt: 'Analyze the task from a technical perspective. Focus on implementation details, code quality, and best practices.',
            temperature: 0.7,
            maxTokens: 2000,
          },
        },
      },
      {
        id: 'agent-2-claude',
        type: 'custom',
        position: { x: 500, y: 250 },
        data: {
          label: 'Claude 3.5 Sonnet',
          type: 'anthropicClaude',
          status: 'idle',
          config: {
            model: 'claude-3-5-sonnet',
            prompt: 'Analyze the task from a strategic perspective. Consider architecture, scalability, and long-term implications.',
            temperature: 0.8,
            maxTokens: 2000,
          },
        },
      },
      {
        id: 'agent-3-gemini',
        type: 'custom',
        position: { x: 500, y: 400 },
        data: {
          label: 'Gemini 1.5 Pro',
          type: 'googleGemini',
          status: 'idle',
          config: {
            model: 'gemini-1.5-pro',
            prompt: 'Analyze the task from a creative perspective. Suggest innovative approaches and alternative solutions.',
            temperature: 0.9,
            maxTokens: 2000,
          },
        },
      },
      {
        id: 'aggregator',
        type: 'custom',
        position: { x: 750, y: 250 },
        data: {
          label: 'Response Aggregator',
          type: 'merge',
          status: 'idle',
          config: {
            strategy: 'combine_all',
          },
        },
      },
      {
        id: 'synthesizer',
        type: 'custom',
        position: { x: 1000, y: 250 },
        data: {
          label: 'Final Synthesizer',
          type: 'openai',
          status: 'idle',
          config: {
            model: 'gpt-4o',
            prompt: 'Synthesize the responses from all agents into a coherent, comprehensive answer. Include insights from all perspectives and provide a balanced recommendation.',
            temperature: 0.5,
            maxTokens: 3000,
          },
        },
      },
      {
        id: 'output-report',
        type: 'custom',
        position: { x: 1250, y: 200 },
        data: {
          label: 'Generate Report',
          type: 'template',
          status: 'idle',
          config: {
            template: 'moa_report',
          },
        },
      },
      {
        id: 'output-console',
        type: 'custom',
        position: { x: 1250, y: 300 },
        data: {
          label: 'Display Results',
          type: 'console',
          status: 'idle',
          config: {},
        },
      },
    ],
    edges: [
      { id: 'e1-2', source: 'task-input', target: 'moa-coordinator', type: 'default' },
      { id: 'e2-3', source: 'moa-coordinator', target: 'agent-1-openai', type: 'default' },
      { id: 'e2-4', source: 'moa-coordinator', target: 'agent-2-claude', type: 'default' },
      { id: 'e2-5', source: 'moa-coordinator', target: 'agent-3-gemini', type: 'default' },
      { id: 'e3-6', source: 'agent-1-openai', target: 'aggregator', type: 'default' },
      { id: 'e4-6', source: 'agent-2-claude', target: 'aggregator', type: 'default' },
      { id: 'e5-6', source: 'agent-3-gemini', target: 'aggregator', type: 'default' },
      { id: 'e6-7', source: 'aggregator', target: 'synthesizer', type: 'default' },
      { id: 'e7-8', source: 'synthesizer', target: 'output-report', type: 'default' },
      { id: 'e7-9', source: 'synthesizer', target: 'output-console', type: 'default' },
    ],
  },
  {
    id: 'local-rag-complete',
    name: '📚 Complete Local RAG System',
    description: 'Full RAG implementation with local embeddings, ChromaDB, and retrieval',
    category: 'rag',
    tags: ['rag', 'embeddings', 'local', 'chromadb', 'semantic-search'],
    difficulty: 'advanced',
    estimatedTime: '5-10 min',
    useCases: ['Document Q&A', 'Knowledge Base Search', 'Semantic Document Retrieval'],
    nodes: [
      {
        id: 'doc-upload',
        type: 'custom',
        position: { x: 50, y: 150 },
        data: {
          label: 'Upload Documents',
          type: 'fileUpload',
          status: 'idle',
          config: { accept: '.pdf,.txt,.md,.docx' },
        },
      },
      {
        id: 'text-extract',
        type: 'custom',
        position: { x: 250, y: 150 },
        data: {
          label: 'Extract Text',
          type: 'pdfExtract',
          status: 'idle',
          config: {},
        },
      },
      {
        id: 'chunk-docs',
        type: 'custom',
        position: { x: 450, y: 150 },
        data: {
          label: 'Chunk Text',
          type: 'textChunker',
          status: 'idle',
          config: { 
            chunkSize: 512, 
            overlap: 50,
            strategy: 'sentence'
          },
        },
      },
      {
        id: 'generate-embeddings',
        type: 'custom',
        position: { x: 650, y: 150 },
        data: {
          label: 'Generate Embeddings',
          type: 'embeddings',
          status: 'idle',
          config: { 
            model: 'text-embedding-ada-002',
            dimensions: 1536
          },
        },
      },
      {
        id: 'store-chroma',
        type: 'custom',
        position: { x: 850, y: 150 },
        data: {
          label: 'Store in ChromaDB',
          type: 'chromadb',
          status: 'idle',
          config: { 
            collection: 'documents',
            operation: 'add'
          },
        },
      },
      {
        id: 'user-query',
        type: 'custom',
        position: { x: 50, y: 350 },
        data: {
          label: 'User Question',
          type: 'textInput',
          status: 'idle',
          config: { placeholder: 'Ask a question about your documents...' },
        },
      },
      {
        id: 'query-embed',
        type: 'custom',
        position: { x: 250, y: 350 },
        data: {
          label: 'Embed Query',
          type: 'embeddings',
          status: 'idle',
          config: { model: 'text-embedding-ada-002' },
        },
      },
      {
        id: 'semantic-search',
        type: 'custom',
        position: { x: 450, y: 350 },
        data: {
          label: 'Semantic Search',
          type: 'chromadb',
          status: 'idle',
          config: { 
            operation: 'query',
            k: 5,
            threshold: 0.7
          },
        },
      },
      {
        id: 'context-builder',
        type: 'custom',
        position: { x: 650, y: 350 },
        data: {
          label: 'Build Context',
          type: 'template',
          status: 'idle',
          config: { 
            template: 'Context: {{results}}\\n\\nQuestion: {{query}}'
          },
        },
      },
      {
        id: 'rag-llm',
        type: 'custom',
        position: { x: 850, y: 350 },
        data: {
          label: 'GPT-4 Answer',
          type: 'openai',
          status: 'idle',
          config: {
            model: 'gpt-4o',
            prompt: 'Answer the question based only on the provided context.',
            temperature: 0.3
          },
        },
      },
      {
        id: 'final-output',
        type: 'custom',
        position: { x: 1050, y: 350 },
        data: {
          label: 'Display Answer',
          type: 'console',
          status: 'idle',
          config: {},
        },
      },
    ],
    edges: [
      { id: 'e1', source: 'doc-upload', target: 'text-extract', type: 'default' },
      { id: 'e2', source: 'text-extract', target: 'chunk-docs', type: 'default' },
      { id: 'e3', source: 'chunk-docs', target: 'generate-embeddings', type: 'default' },
      { id: 'e4', source: 'generate-embeddings', target: 'store-chroma', type: 'default' },
      { id: 'e5', source: 'user-query', target: 'query-embed', type: 'default' },
      { id: 'e6', source: 'query-embed', target: 'semantic-search', type: 'default' },
      { id: 'e7', source: 'semantic-search', target: 'context-builder', type: 'default' },
      { id: 'e8', source: 'context-builder', target: 'rag-llm', type: 'default' },
      { id: 'e9', source: 'rag-llm', target: 'final-output', type: 'default' },
    ],
  },
  {
    id: 'api-integration-workflow',
    name: '🔌 REST API Integration',
    description: 'Connect to external APIs, process data, and store results',
    category: 'integration',
    tags: ['api', 'rest', 'integration', 'webhook'],
    difficulty: 'intermediate',
    estimatedTime: '3-5 min',
    useCases: ['API Data Sync', 'Third-party Integration', 'Webhook Processing'],
    nodes: [
      {
        id: 'api-trigger',
        type: 'custom',
        position: { x: 50, y: 150 },
        data: {
          label: 'API Request',
          type: 'apiRequest',
          status: 'idle',
          config: {
            url: 'https://api.example.com/data',
            method: 'GET',
            headers: { 'Content-Type': 'application/json' }
          },
        },
      },
      {
        id: 'response-validate',
        type: 'custom',
        position: { x: 250, y: 150 },
        data: {
          label: 'Validate Response',
          type: 'validator',
          status: 'idle',
          config: { schema: 'json' },
        },
      },
      {
        id: 'data-transform',
        type: 'custom',
        position: { x: 450, y: 150 },
        data: {
          label: 'Transform Data',
          type: 'jsonTransform',
          status: 'idle',
          config: {},
        },
      },
      {
        id: 'conditional-route',
        type: 'custom',
        position: { x: 650, y: 150 },
        data: {
          label: 'Route by Type',
          type: 'conditional',
          status: 'idle',
          config: { field: 'type' },
        },
      },
      {
        id: 'db-store',
        type: 'custom',
        position: { x: 850, y: 100 },
        data: {
          label: 'PostgreSQL',
          type: 'postgresql',
          status: 'idle',
          config: { table: 'api_data' },
        },
      },
      {
        id: 'cache-store',
        type: 'custom',
        position: { x: 850, y: 200 },
        data: {
          label: 'Redis Cache',
          type: 'redis',
          status: 'idle',
          config: { ttl: 3600 },
        },
      },
      {
        id: 'webhook-notify',
        type: 'custom',
        position: { x: 1050, y: 150 },
        data: {
          label: 'Webhook Notify',
          type: 'webhook',
          status: 'idle',
          config: {},
        },
      },
    ],
    edges: [
      { id: 'e1', source: 'api-trigger', target: 'response-validate', type: 'default' },
      { id: 'e2', source: 'response-validate', target: 'data-transform', type: 'default' },
      { id: 'e3', source: 'data-transform', target: 'conditional-route', type: 'default' },
      { id: 'e4', source: 'conditional-route', target: 'db-store', type: 'default' },
      { id: 'e5', source: 'conditional-route', target: 'cache-store', type: 'default' },
      { id: 'e6', source: 'db-store', target: 'webhook-notify', type: 'default' },
      { id: 'e7', source: 'cache-store', target: 'webhook-notify', type: 'default' },
    ],
  },
  {
    id: 'chatbot-with-memory',
    name: '💬 Chatbot with Memory',
    description: 'Conversational AI with persistent memory and context',
    category: 'advanced',
    tags: ['chatbot', 'conversation', 'memory', 'ai'],
    difficulty: 'intermediate',
    estimatedTime: '5 min',
    useCases: ['Customer Support Bot', 'Personal Assistant', 'Interactive Q&A'],
    nodes: [
      {
        id: 'user-message',
        type: 'custom',
        position: { x: 50, y: 200 },
        data: {
          label: 'User Message',
          type: 'textInput',
          status: 'idle',
          config: {},
        },
      },
      {
        id: 'load-history',
        type: 'custom',
        position: { x: 250, y: 150 },
        data: {
          label: 'Load Chat History',
          type: 'cache',
          status: 'idle',
          config: { key: 'chat_history' },
        },
      },
      {
        id: 'context-prep',
        type: 'custom',
        position: { x: 250, y: 250 },
        data: {
          label: 'Prepare Context',
          type: 'template',
          status: 'idle',
          config: {},
        },
      },
      {
        id: 'merge-context',
        type: 'custom',
        position: { x: 450, y: 200 },
        data: {
          label: 'Merge Context',
          type: 'merge',
          status: 'idle',
          config: {},
        },
      },
      {
        id: 'chatbot-ai',
        type: 'custom',
        position: { x: 650, y: 200 },
        data: {
          label: 'Claude Chat',
          type: 'anthropicClaude',
          status: 'idle',
          config: { 
            model: 'claude-3-5-sonnet',
            systemPrompt: 'You are a helpful assistant.',
            temperature: 0.7
          },
        },
      },
      {
        id: 'save-history',
        type: 'custom',
        position: { x: 850, y: 200 },
        data: {
          label: 'Update History',
          type: 'cache',
          status: 'idle',
          config: { 
            key: 'chat_history',
            operation: 'append'
          },
        },
      },
      {
        id: 'response-out',
        type: 'custom',
        position: { x: 1050, y: 200 },
        data: {
          label: 'Bot Response',
          type: 'console',
          status: 'idle',
          config: {},
        },
      },
    ],
    edges: [
      { id: 'e1', source: 'user-message', target: 'load-history', type: 'default' },
      { id: 'e2', source: 'user-message', target: 'context-prep', type: 'default' },
      { id: 'e3', source: 'load-history', target: 'merge-context', type: 'default' },
      { id: 'e4', source: 'context-prep', target: 'merge-context', type: 'default' },
      { id: 'e5', source: 'merge-context', target: 'chatbot-ai', type: 'default' },
      { id: 'e6', source: 'chatbot-ai', target: 'save-history', type: 'default' },
      { id: 'e7', source: 'save-history', target: 'response-out', type: 'default' },
    ],
  },
  {
    id: 'batch-processing',
    name: '⚡ Batch Data Processing',
    description: 'Process large datasets in parallel with error handling',
    category: 'data',
    tags: ['batch', 'parallel', 'data-processing', 'scale'],
    difficulty: 'advanced',
    estimatedTime: '10+ min',
    useCases: ['Bulk Data Import', 'Mass Email Processing', 'Report Generation'],
    nodes: [
      {
        id: 'data-source',
        type: 'custom',
        position: { x: 50, y: 200 },
        data: {
          label: 'CSV Data Source',
          type: 'csvReader',
          status: 'idle',
          config: { batchSize: 100 },
        },
      },
      {
        id: 'batch-split',
        type: 'custom',
        position: { x: 250, y: 200 },
        data: {
          label: 'Split into Batches',
          type: 'batchSplitter',
          status: 'idle',
          config: { size: 10 },
        },
      },
      {
        id: 'parallel-1',
        type: 'custom',
        position: { x: 450, y: 100 },
        data: {
          label: 'Process Batch 1',
          type: 'openai',
          status: 'idle',
          config: { model: 'gpt-4o-mini' },
        },
      },
      {
        id: 'parallel-2',
        type: 'custom',
        position: { x: 450, y: 175 },
        data: {
          label: 'Process Batch 2',
          type: 'openai',
          status: 'idle',
          config: { model: 'gpt-4o-mini' },
        },
      },
      {
        id: 'parallel-3',
        type: 'custom',
        position: { x: 450, y: 250 },
        data: {
          label: 'Process Batch 3',
          type: 'openai',
          status: 'idle',
          config: { model: 'gpt-4o-mini' },
        },
      },
      {
        id: 'error-handler',
        type: 'custom',
        position: { x: 650, y: 300 },
        data: {
          label: 'Error Handler',
          type: 'errorHandler',
          status: 'idle',
          config: { retry: 3 },
        },
      },
      {
        id: 'merge-results',
        type: 'custom',
        position: { x: 650, y: 175 },
        data: {
          label: 'Merge Results',
          type: 'merge',
          status: 'idle',
          config: {},
        },
      },
      {
        id: 'write-output',
        type: 'custom',
        position: { x: 850, y: 175 },
        data: {
          label: 'Write to CSV',
          type: 'fileWrite',
          status: 'idle',
          config: { format: 'csv' },
        },
      },
    ],
    edges: [
      { id: 'e1', source: 'data-source', target: 'batch-split', type: 'default' },
      { id: 'e2', source: 'batch-split', target: 'parallel-1', type: 'default' },
      { id: 'e3', source: 'batch-split', target: 'parallel-2', type: 'default' },
      { id: 'e4', source: 'batch-split', target: 'parallel-3', type: 'default' },
      { id: 'e5', source: 'parallel-1', target: 'merge-results', type: 'default' },
      { id: 'e6', source: 'parallel-2', target: 'merge-results', type: 'default' },
      { id: 'e7', source: 'parallel-3', target: 'merge-results', type: 'default' },
      { id: 'e8', source: 'parallel-1', target: 'error-handler', type: 'default', label: 'on error' },
      { id: 'e9', source: 'parallel-2', target: 'error-handler', type: 'default', label: 'on error' },
      { id: 'e10', source: 'parallel-3', target: 'error-handler', type: 'default', label: 'on error' },
      { id: 'e11', source: 'merge-results', target: 'write-output', type: 'default' },
    ],
  },
  {
    id: 'moa-simple-2-agents',
    name: '🤝 MOA - Simple (2 Agents)',
    description: 'Simplified MOA workflow with 2 AI agents for faster processing',
    category: 'advanced',
    tags: ['moa', 'multi-agent', 'ensemble', 'ai'],
    difficulty: 'advanced',
    estimatedTime: '3-5 min',
    useCases: ['Complex Decision Making', 'Multi-perspective Analysis', 'Quality Assurance'],
    nodes: [
      {
        id: 'task-input',
        type: 'custom',
        position: { x: 50, y: 200 },
        data: {
          label: 'Task Input',
          type: 'textInput',
          status: 'idle',
          config: {},
        },
      },
      {
        id: 'agent-1-openai',
        type: 'custom',
        position: { x: 300, y: 150 },
        data: {
          label: 'OpenAI GPT-4o',
          type: 'openai',
          status: 'idle',
          config: {
            model: 'gpt-4o',
            prompt: 'Provide a detailed technical analysis of the task.',
            temperature: 0.7,
            maxTokens: 2000,
          },
        },
      },
      {
        id: 'agent-2-claude',
        type: 'custom',
        position: { x: 300, y: 250 },
        data: {
          label: 'Claude 3.5 Sonnet',
          type: 'anthropicClaude',
          status: 'idle',
          config: {
            model: 'claude-3-5-sonnet',
            prompt: 'Provide a strategic and creative perspective on the task.',
            temperature: 0.8,
            maxTokens: 2000,
          },
        },
      },
      {
        id: 'aggregator',
        type: 'custom',
        position: { x: 550, y: 200 },
        data: {
          label: 'Merge Responses',
          type: 'merge',
          status: 'idle',
          config: {},
        },
      },
      {
        id: 'synthesizer',
        type: 'custom',
        position: { x: 800, y: 200 },
        data: {
          label: 'Synthesize Answer',
          type: 'openai',
          status: 'idle',
          config: {
            model: 'gpt-4o-mini',
            prompt: 'Combine both perspectives into a comprehensive answer.',
            temperature: 0.5,
            maxTokens: 2000,
          },
        },
      },
      {
        id: 'output',
        type: 'custom',
        position: { x: 1050, y: 200 },
        data: {
          label: 'Final Output',
          type: 'console',
          status: 'idle',
          config: {},
        },
      },
    ],
    edges: [
      { id: 'e1-2', source: 'task-input', target: 'agent-1-openai', type: 'default' },
      { id: 'e1-3', source: 'task-input', target: 'agent-2-claude', type: 'default' },
      { id: 'e2-4', source: 'agent-1-openai', target: 'aggregator', type: 'default' },
      { id: 'e3-4', source: 'agent-2-claude', target: 'aggregator', type: 'default' },
      { id: 'e4-5', source: 'aggregator', target: 'synthesizer', type: 'default' },
      { id: 'e5-6', source: 'synthesizer', target: 'output', type: 'default' },
    ],
  },
]
