"""
PC Utility Backend Installer Creator
This script creates a standalone executable and Windows installer using PyInstaller and Inno Setup.

Requirements:
- PyInstaller: pip install pyinstaller
- Inno Setup: https://jrsoftware.org/isdl.php (Windows only)

Usage:
    python create_installer.py
"""

import os
import sys
import subprocess
import shutil
from pathlib import Path

# Configuration
APP_NAME = "PCUtilityBackend"
APP_VERSION = "1.0.0"
APP_AUTHOR = "Node'y Team"
MAIN_SCRIPT = "../pc_utility_backend/app.py"
OUTPUT_DIR = "dist"
BUILD_DIR = "build"

def check_requirements():
    """Check if required tools are installed"""
    print("Checking requirements...")
    
    # Check Python version
    if sys.version_info < (3, 8):
        print("Error: Python 3.8 or higher is required")
        return False
    
    # Check if PyInstaller is installed
    try:
        import PyInstaller
        print(f"✓ PyInstaller {PyInstaller.__version__} found")
    except ImportError:
        print("✗ PyInstaller not found")
        print("  Install with: pip install pyinstaller")
        return False
    
    # Check if main script exists
    if not os.path.exists(MAIN_SCRIPT):
        print(f"✗ Main script not found: {MAIN_SCRIPT}")
        return False
    
    print(f"✓ Main script found: {MAIN_SCRIPT}")
    
    return True

def create_executable():
    """Create standalone executable using PyInstaller"""
    print("\n" + "=" * 60)
    print("Creating standalone executable with PyInstaller...")
    print("=" * 60 + "\n")
    
    # PyInstaller command
    cmd = [
        "pyinstaller",
        "--name", APP_NAME,
        "--onefile",
        "--console",
        "--clean",
        f"--distpath={OUTPUT_DIR}",
        f"--workpath={BUILD_DIR}",
        MAIN_SCRIPT,
    ]
    
    # Add icon if exists
    icon_path = "assets/icon.ico"
    if os.path.exists(icon_path):
        cmd.extend(["--icon", icon_path])
        print(f"Using icon: {icon_path}")
    
    # Add hidden imports for dependencies
    hidden_imports = [
        "fastapi",
        "uvicorn",
        "psutil",
        "GPUtil",
        "transformers",
        "torch",
        "pydantic",
    ]
    
    for module in hidden_imports:
        cmd.extend(["--hidden-import", module])
    
    print("Running PyInstaller...")
    print(" ".join(cmd))
    print()
    
    result = subprocess.run(cmd)
    
    if result.returncode != 0:
        print("\n✗ PyInstaller failed")
        return False
    
    print("\n✓ Executable created successfully")
    return True

def create_inno_setup_script():
    """Create Inno Setup script for Windows installer"""
    print("\n" + "=" * 60)
    print("Creating Inno Setup script...")
    print("=" * 60 + "\n")
    
    script_content = f"""
; PC Utility Backend Installer Script
; Generated by create_installer.py

#define MyAppName "{APP_NAME}"
#define MyAppVersion "{APP_VERSION}"
#define MyAppPublisher "{APP_AUTHOR}"
#define MyAppExeName "{APP_NAME}.exe"

[Setup]
AppId={{{{5E5F9A2C-3D4E-4F5A-9B6C-7D8E9F0A1B2C}}
AppName={{#MyAppName}}
AppVersion={{#MyAppVersion}}
AppPublisher={{#MyAppPublisher}}
DefaultDirName={{autopf}}\\{{#MyAppName}}
DefaultGroupName={{#MyAppName}}
OutputDir=.
OutputBaseFilename=PCUtilityBackend_Setup
Compression=lzma
SolidCompression=yes
WizardStyle=modern

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{{cm:CreateDesktopIcon}}"; GroupDescription: "{{cm:AdditionalIcons}}"; Flags: unchecked

[Files]
Source: "{OUTPUT_DIR}\\{{#MyAppExeName}}"; DestDir: "{{app}}"; Flags: ignoreversion

[Icons]
Name: "{{group}}\\{{#MyAppName}}"; Filename: "{{app}}\\{{#MyAppExeName}}"
Name: "{{group}}\\{{cm:UninstallProgram,{{#MyAppName}}}}"; Filename: "{{uninstallexe}}"
Name: "{{autodesktop}}\\{{#MyAppName}}"; Filename: "{{app}}\\{{#MyAppExeName}}"; Tasks: desktopicon

[Run]
Filename: "{{app}}\\{{#MyAppExeName}}"; Description: "{{cm:LaunchProgram,{{#StringChange(MyAppName, '&', '&&')}}}}"; Flags: nowait postinstall skipifsilent
"""
    
    script_path = "setup.iss"
    with open(script_path, 'w') as f:
        f.write(script_content.strip())
    
    print(f"✓ Inno Setup script created: {script_path}")
    return script_path

def create_installer():
    """Create Windows installer using Inno Setup"""
    print("\n" + "=" * 60)
    print("Creating Windows installer...")
    print("=" * 60 + "\n")
    
    # Check if Inno Setup is installed
    inno_setup_paths = [
        r"C:\Program Files (x86)\Inno Setup 6\ISCC.exe",
        r"C:\Program Files\Inno Setup 6\ISCC.exe",
        r"C:\Program Files (x86)\Inno Setup 5\ISCC.exe",
        r"C:\Program Files\Inno Setup 5\ISCC.exe",
    ]
    
    iscc_path = None
    for path in inno_setup_paths:
        if os.path.exists(path):
            iscc_path = path
            break
    
    if not iscc_path:
        print("✗ Inno Setup not found")
        print("  Download from: https://jrsoftware.org/isdl.php")
        print("  The executable is available in:", OUTPUT_DIR)
        return False
    
    print(f"✓ Inno Setup found: {iscc_path}")
    
    # Create Inno Setup script
    script_path = create_inno_setup_script()
    
    # Run Inno Setup compiler
    cmd = [iscc_path, script_path]
    
    print("Running Inno Setup compiler...")
    result = subprocess.run(cmd)
    
    if result.returncode != 0:
        print("\n✗ Inno Setup compilation failed")
        return False
    
    print("\n✓ Installer created successfully")
    return True

def cleanup():
    """Clean up build artifacts"""
    print("\n" + "=" * 60)
    print("Cleaning up...")
    print("=" * 60 + "\n")
    
    # Remove build directory
    if os.path.exists(BUILD_DIR):
        shutil.rmtree(BUILD_DIR)
        print(f"✓ Removed {BUILD_DIR}")
    
    # Remove spec file
    spec_file = f"{APP_NAME}.spec"
    if os.path.exists(spec_file):
        os.remove(spec_file)
        print(f"✓ Removed {spec_file}")

def main():
    """Main installation script"""
    print("=" * 60)
    print("PC Utility Backend Installer Creator")
    print("=" * 60 + "\n")
    
    # Check requirements
    if not check_requirements():
        print("\n✗ Requirements check failed")
        return 1
    
    # Create executable
    if not create_executable():
        print("\n✗ Executable creation failed")
        return 1
    
    # Create installer (Windows only)
    if sys.platform == "win32":
        create_installer()
    else:
        print("\nNote: Windows installer creation skipped (not on Windows)")
        print(f"Executable available in: {OUTPUT_DIR}/{APP_NAME}")
    
    # Cleanup
    cleanup()
    
    print("\n" + "=" * 60)
    print("Installation package created successfully!")
    print("=" * 60)
    print(f"\nExecutable: {OUTPUT_DIR}/{APP_NAME}")
    if sys.platform == "win32":
        print("Installer: PCUtilityBackend_Setup.exe")
    print()
    
    return 0

if __name__ == "__main__":
    sys.exit(main())
